Update lint.yml

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -25,13 +25,12 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          # super-linter needs the full git history to get the
-          # list of files that changed across commits
           fetch-depth: 0
 
       # Cache Docker layers for the super-linter image
       - name: Cache Docker layers
-        uses: actions/cache@v3
+        id: cache-docker
+        uses: actions/cache@v4
         with:
           path: /tmp/.docker-cache
           key: docker-super-linter-${{ runner.os }}-${{ hashFiles('Dockerfile') }}-${{ env.LINTER_VERSION }}
@@ -40,28 +39,25 @@ jobs:
 
       # Load cached Docker layers if available
       - name: Load Docker cache
-        if: steps.cache.outputs.cache-hit != 'true'
+        if: steps.cache-docker.outputs.cache-hit == 'true'
         run: |
-          mkdir -p /tmp/.docker-cache
-          docker load -i /tmp/.docker-cache/super-linter.tar || echo "No cache found, pulling image."
+          docker load -i /tmp/.docker-cache/super-linter.tar || echo "Cache not found."
 
       # Pull Docker image or use cached layers
       - name: Pull Super-linter Docker image
+        if: steps.cache-docker.outputs.cache-hit != 'true'
         run: |
-          if [ -f /tmp/.docker-cache/super-linter.tar ]; then
-            echo "Image loaded from cache.";
-          else
-            docker pull ghcr.io/super-linter/super-linter:${{ env.LINTER_VERSION }};
-            docker save ghcr.io/super-linter/super-linter:${{ env.LINTER_VERSION }} -o /tmp/.docker-cache/super-linter.tar;
-          fi
+          docker pull ghcr.io/super-linter/super-linter:${{ env.LINTER_VERSION }}
+          mkdir -p /tmp/.docker-cache
+          docker save ghcr.io/super-linter/super-linter:${{ env.LINTER_VERSION }} -o /tmp/.docker-cache/super-linter.tar
 
       # Run Super-linter
       - name: Super-linter
-        run: |
-          docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
-            -e VALIDATE_BASH_EXEC=false \
-            -e VALIDATE_DOCKERFILE_HADOLINT=true \
-            -e VALIDATE_SHELL_SHFMT=false \
-            -e VALIDATE_YAML_PRETTIER=true \
-            -e DEFAULT_WORKSPACE=/tmp/lint \
-            ghcr.io/super-linter/super-linter:${{ env.LINTER_VERSION }}
+        uses: super-linter/super-linter@v7.1.0 # x-release-please-version
+        env:
+          # To report GitHub Actions status checks
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          #VALIDATE_BASH_EXEC: true
+          VALIDATE_DOCKERFILE_HADOLINT: true
+          #VALIDATE_SHELL_SHFMT: true
+          VALIDATE_YAML_PRETTIER: true
